var GAME_LEVELS = [
   ["                                                                               ",
   "            v                     v                             o               ",
   "                                                                                ",
   "                                                                                ",
   "                                                         xxxxxxxxxxxx           ",
   "                    yyyyy                         xxxxxxxxxxxxxxxxxx            ",
   "                                                        xxxxxxxxxxx             ",
   "                                                            xxxx                ",
   "                                       xxxxx                                    ",
   "          yyyyy                         xxx                                     ",
   "         yyyyyyy           xxx                    y   yyy                       ",
   "          yyyyy             x                     yyyyyyy                       ",
   "                                                   yyyy                         ",
   "                                 xxxxx                                          ",
   "   xxx                             xxxxx                                        ",
   "    x                               !!!!                  xxxxx                 ",
   "                 xxxxx                                     xxx                  ",
   "     @      g     xxx                                                           ",
   "  xxxxxx                                                   xxxxxxx              ",
   "         xxxx                               L  xxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "     xxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx     ",
   "          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                             o                                    ",
   "                                                                                                                  ",
   "       xxx                                                         xxxx            x                              ",
   "     xxxxxxxxxx                                                  xxxxxx!!!!!xxxxxxxxx                             ",
   "       xxxxxx!                                                       xxxxxxxxxxxxxxxxxxxx                         ",
   "             !                                          yyy              xxxxxxx                                  ",
   "             !                                           y                                                        ",
   "             !       xxxx L                L xxxxxx                                                               ",
   "             !    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                  ",
   "             !   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                xxx               ",
   "             !                                                                                   x                ",
   "            xxx                                                                                                   ",
   "           xxxxx                                                            xxx                                   ",
   "                                                                             x                          yyyy      ",
   "              y         yyyyyyy                              g                                           yy       ",
   "             yyyyyyyyyyyyyyyyyyyy                      @                                                          ",
   "                                        xxx     x     xxx   xxx     xxx                                           ",
   "                                       xxxx!!!!!x!!!!!!!!!!!xxx!!!!!xxxx                                g         ",
   "                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ",
   "                                            xxxxxxxxxxx!xxxxxxxxxx              yyy           L     yyyyyyyyy     ",
   "                                 xxx                   !                       yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy     ",
   "                  g               x                    !                          yyyyyyyyyyyyyyyyyyyyyyyy        ",
   " y                          y                                                                                     ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxx          yyy                                                                        ",
   "                yyyyyyyyy               y                                                                         ",
   "                                                                   xxx                                            ",
   "                                                  xxx               x                                             ",
   "                                                   x                                                              ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                           yyy                                                    ",
   "                                                            y                                                     ",
   "                                                                                                                  ",],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                              xxx       o       xxx                                                           ",
   "                             x!!!x             x!!!x                                                          ",
   "                               v        x        v                                                            ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                                                                    ",
   "                                       x x                                                                    ",
   "                                     xxx xxx                                   g                              ",
   "                                      x!!!x                                   xxx                             ",
   "                                      x!!!x                                  x!!!x                            ",
   "                                      x!!!x                                   v                               ",
   "                                     xx!!!xx                                                                  ",
   "                                      x!!!xx                                                                  ",
   "                                      x!!!x                                                                   ",
   "                                      x!!!x                                                                   ",
   "                                     xx!!!xx                                                                  ",
   "                                      x!!!x                                                                   ",
   "                                      x!!!x                                                                   ",
   "                                      x!!!x                                                                   ",
   "                                     xx!!!xx                                                                  ",
   "                                      x!!!x                                                                   ",
   "                                      x!!!x                                  g                                ",
   "                                      xx!xx                                                                   ",
   "                                      xxxxx                                 xxx                               ",
   "                                      x!!!x                                  x       g                        ",
   "                                      x!!!x                                                                   ",
   "                                      x!!!x                                         yyy                       ",
   "                                      x!!!x                              g           y                        ",
   "                                      x!v!x                                                                   ",
   "      @                                                                 xxx                                   ",
   "    yyyyy               x                                                x                                    ",
   "     yyy               xxx              g                                                                     ",
   "                     xxxxxx                                 Lxxxxxx                                           ",
   "                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                          ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "      o                                                                                                       ",
   "    xxxxx                                                                                                     ",
   "     xxx                                                                                                      ",
   "                                                                    L                                         ",
   "                                                                   L                                          ",
   "                                                                  L                                           ",
   "                   g                                             L                                            ",
   "                                                                L                                             ",
   "                  xxx                                          L                                              ",
   "                   x                                          L                                               ",
   "                                                             L                                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                             xxx                                              ",
   "                           g                                  x                                               ",
   "                                                                                                              ",
   "                          xxx                                                                                 ",
   "                           x                                                                                  ",
   "                                          x L                                                   Lxxx          ",
   "                                          xxxxxxxxx                                               x           ",
   "                                                                        g                                     ",
   "                                                                                                              ",
   "                                                                    xxxxxxxxx                                 ",
   "                                                                     xxxx                                     ",
   "            g                                                                                                 ",
   "   y             y                                                                                @           ",
   "   xxxxxxxxxxxxxxx                                                                              xxxxx         ",
   "     xxxxxxxxxxx                                                                                 xxx          ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                               ",
   "        !     !     !!!!!    !     !     !             !    !    !!      !   ! ",
   "         !   !     !     !   !     !     !             !    !    ! !     !   ! ",
   "          !!!     !       !  !     !     !      !      !    !    !  !    !   ! ",
   "           !      !       !  !     !     !     ! !     !    !    !   !   !   ! ",
   "           !      !       !  !     !     !    !   !    !    !    !    !  !   ! ",
   "           !       !     !   !     !     !   !     !   !    !    !     ! !     ",
   "           !        !!!!!     !!!!!       !!!       !!!     !    !      !!   ! ",
   "                                                                               ",
   "   @                                                                           ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
